
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 108
#define YY_END_OF_BUFFER 109
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[380] =
    {   0,
        0,    0,    0,    0,    0,    0,  109,  107,    1,    2,
        2,   30,  100,   90,   14,  107,   16,   17,   12,   10,
       18,   11,  107,   13,   91,   91,   32,   23,   15,   24,
       90,   90,   27,   28,   36,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   25,  107,   26,   97,   96,   96,   97,  106,  105,
      105,  101,  104,    1,    2,   29,   90,   19,   46,   47,
       33,   93,    0,   95,   99,   92,    0,    0,    0,   91,
        0,   35,   21,   20,   22,   34,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   61,

       90,   90,   90,   90,   90,   90,   90,   90,    6,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   31,   96,
       98,  106,  105,  103,  102,   93,    0,    0,    0,   99,
       92,    0,    0,   94,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   67,   90,   90,   90,    4,
       90,   90,   75,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   88,
       90,   90,   90,    0,   93,    0,   92,    0,    0,   92,

       94,    0,   90,   90,   90,   90,   90,   90,   90,   54,
       55,   90,   57,   90,   90,   90,   90,   90,    7,   62,
       90,   90,   90,   90,   68,   90,   90,   90,   90,   73,
       90,   48,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   84,   90,   90,    3,   45,   90,   90,
       93,    0,    0,   92,    0,   90,   90,   90,   90,   90,
       90,   53,   56,   38,   58,   90,   90,   90,   90,   64,
       66,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   79,   90,   90,   81,   90,   90,   85,   90,   90,
        8,    0,   90,   44,   50,   90,   52,   90,   90,   90,

        5,   90,   90,   90,   70,   90,   90,   74,   90,   90,
       90,   42,    9,   43,   90,   82,   90,   86,   90,   90,
       39,   49,    0,   90,   37,   90,   60,   63,   65,   90,
       90,   90,   76,   77,   90,   90,   90,   90,   90,    0,
        0,   51,   59,   90,   90,   90,   90,   80,   90,   90,
       89,    0,    0,   90,   90,   72,   78,   90,   87,    0,
        0,   69,   71,   90,    0,    0,   90,    0,    0,   83,
        0,    0,    0,    0,    0,    0,   41,   40,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,    7,    7,    7,    7,   24,    7,
        7,    7,   25,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   26,    7,    7,    7,    7,    7,    7,    7,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,    7,   41,   42,   43,   44,
       45,   46,    7,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    2,    1,    3,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    1,
        1,    1,    1,    4,    4,    4,    1,    3,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1,    1
    } ;

static const flex_int16_t yy_base[386] =
    {   0,
        0,    0,   56,   58,   60,   68,  489,  490,  486,  490,
      484,  464,  490,    0,  490,  476,  490,  490,  490,  471,
      490,   50,   57,   65,   62,   71,  490,   62,  461,   69,
      438,   51,  490,  490,  490,   46,   56,   72,   61,   71,
       76,  436,   82,  435,   91,   88,  443,   90,   83,  433,
      438,  490,  419,  490,  490,  490,  472,  457,    0,  490,
      470,  490,  106,  470,  490,  490,    0,  490,  490,  490,
      490,  127,  435,  490,    0,  113,  138,  146,  129,  152,
      148,  490,  490,  490,  490,  490,  421,  422,  420,  419,
      418,  420,  428,  414,  124,  430,  429,  416,  422,  408,

      409,  406,  406,  412,  409,  407,  404,  401,    0,  403,
      129,  404,  398,  394,  403,  410,   88,  410,  393,  396,
      143,  394,  399,  394,  140,  149,   27,  397,  490,  490,
      490,    0,  490,  490,  490,  173,  183,  175,  392,    0,
      189,  197,  166,  199,  399,  394,  384,  383,  395,  388,
      397,  392,  391,  392,  378,  376,  173,  391,  389,  385,
      377,  383,  370,  385,  384,    0,  370,  144,  365,  377,
      374,  371,    0,  368,  368,  357,  358,  364,  355,  357,
      354,  362,  365,  351,  365,  350,  352,  352,  359,    0,
      359,  361,  350,  205,  208,  353,  210,  213,  217,  219,

      224,  229,  352,  345,  352,  340,  339,  349,  343,    0,
        0,  344,    0,  334,  332,  340,  329,  336,    0,    0,
      333,  340,  333,  325,    0,  337,  325,  339,  323,    0,
      318,    0,  336,  335,  330,  325,  317,  314,  322,  327,
      313,  325,  319,    0,  305,  308,    0,    0,  306,  318,
      233,  235,  304,  238,  240,  316,  313,  307,  317,  299,
      315,    0,    0,    0,    0,  302,  303,  308,  308,  300,
        0,  298,  291,  295,  301,  301,  298,  286,  300,  299,
      288,    0,  297,  281,    0,  290,  281,  279,  286,  285,
        0,  285,  276,    0,  306,  287,    0,  276,  269,  269,

        0,  269,  262,  279,    0,  280,  281,    0,  276,  275,
      261,    0,    0,    0,  272,    0,  263,    0,  271,  264,
      490,  289,  259,  254,    0,  266,    0,    0,    0,  257,
      264,  265,    0,    0,  262,  251,  252,  251,  258,  247,
      242,    0,    0,  240,  240,  246,  246,    0,  230,  219,
        0,  235,  216,  215,  225,    0,    0,  206,    0,  202,
      229,    0,    0,  204,  185,  173,  179,  175,  158,    0,
      175,  155,  138,  108,   87,   60,  490,  490,  490,  271,
      275,   81,  279,  283,  287
    } ;

static const flex_int16_t yy_def[386] =
    {   0,
      379,    1,  380,  380,  381,  381,  379,  379,  379,  379,
      379,  379,  379,  382,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      382,  382,  379,  379,  379,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  379,  379,  379,  379,  379,  379,  379,  383,  379,
      379,  379,  384,  379,  379,  379,  382,  379,  379,  379,
      379,  379,  379,  379,  385,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,

      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  379,  379,
      379,  383,  379,  379,  379,  379,  379,  379,  379,  385,
      379,  379,  379,  379,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  379,  379,  379,  379,  379,  379,  379,

      379,  379,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      379,  379,  379,  379,  379,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  379,  382,  382,  382,  382,  382,  382,  382,  382,

      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      379,  382,  379,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  379,
      379,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  379,  379,  382,  382,  382,  382,  382,  382,  379,
      379,  382,  382,  382,  379,  379,  382,  379,  379,  382,
      379,  379,  379,  379,  379,  379,  379,  379,    0,  379,
      379,  379,  379,  379,  379
    } ;

static const flex_int16_t yy_nxt[549] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   14,   31,   32,   33,    8,   34,   35,
       14,   36,   37,   38,   39,   40,   41,   42,   14,   43,
       14,   44,   14,   45,   14,   46,   47,   48,   49,   14,
       50,   51,   14,   14,   14,   52,   53,   54,   56,   57,
       56,   57,   60,   61,   70,   62,  191,   58,  192,   58,
       60,   61,   71,   62,   72,   72,   74,   76,   90,   77,
       77,   75,   82,   83,   67,   78,   76,   63,   80,   80,
       85,   86,   79,   91,   78,   63,   99,   78,   73,   88,

       92,   81,   93,   95,   89,  100,   78,  104,  378,   94,
       96,  135,  101,   97,  102,  105,   98,  106,  109,  116,
      107,  125,  113,  103,  110,  111,  114,  176,  120,  126,
      141,  141,  177,  135,  117,  377,  142,  118,  121,  122,
      115,  123,  135,  124,  136,  136,   77,   77,  142,  135,
      137,  376,  135,   76,  135,   77,   77,  138,  143,   79,
      143,   78,  137,  144,  144,   80,   80,   76,   79,   80,
       80,  153,  154,   78,  181,   78,  169,  170,   81,  186,
      188,  375,   81,  144,  144,  226,  187,   78,  227,  182,
      136,  136,  136,  136,  374,  194,  137,  194,  189,  373,

      195,  195,  190,  138,  372,  138,  197,  197,  137,  199,
      371,  199,  142,  370,  200,  200,  201,  201,  369,  198,
      215,  216,  195,  195,  142,  251,  251,  197,  197,  202,
      197,  197,  368,  142,  200,  200,  254,  254,  252,  367,
      198,  201,  201,  198,  366,  142,  201,  201,  365,  255,
      251,  251,  251,  251,  202,  254,  254,  254,  254,  202,
      364,  363,  362,  252,  361,  252,  360,  359,  255,  358,
      255,   55,   55,   55,   55,   59,   59,   59,   59,  132,
      357,  356,  132,  134,  355,  134,  134,  140,  354,  140,
      140,  353,  352,  351,  350,  349,  348,  347,  346,  345,

      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  247,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      253,  250,  249,  248,  247,  246,  245,  244,  243,  242,

      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  225,  224,  223,  222,  221,  220,
      219,  218,  217,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  196,  193,  185,  184,  183,
      180,  179,  178,  175,  174,  173,  172,  171,  168,  167,
      166,  165,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  152,  151,  150,  149,  148,  147,  146,  145,
      139,   64,  133,  131,  130,  129,  128,  127,  119,  112,
      108,   87,   84,   69,   68,   66,   65,   64,  379,    7,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,

      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379
    } ;

static const flex_int16_t yy_chk[549] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        4,    4,    5,    5,   22,    5,  127,    3,  127,    4,
        6,    6,   22,    6,   23,   23,   24,   25,   36,   25,
       25,   24,   28,   28,  382,   25,   26,    5,   26,   26,
       30,   30,   25,   36,   26,    6,   39,   25,   23,   32,

       37,   26,   37,   38,   32,   39,   26,   41,  376,   37,
       38,   63,   40,   38,   40,   41,   38,   41,   43,   46,
       41,   49,   45,   40,   43,   43,   45,  117,   48,   49,
       76,   76,  117,   63,   46,  375,   76,   46,   48,   48,
       45,   48,   63,   48,   72,   72,   79,   79,   76,   63,
       72,  374,   63,   77,   63,   77,   77,   72,   78,   79,
       78,   77,   72,   78,   78,   81,   81,   80,   77,   80,
       80,   95,   95,   77,  121,   80,  111,  111,   81,  125,
      126,  373,   80,  143,  143,  168,  125,   80,  168,  121,
      136,  136,  138,  138,  372,  137,  136,  137,  126,  371,

      137,  137,  126,  136,  369,  138,  141,  141,  136,  142,
      368,  142,  141,  367,  142,  142,  144,  144,  366,  141,
      157,  157,  194,  194,  141,  195,  195,  197,  197,  144,
      198,  198,  365,  197,  199,  199,  200,  200,  195,  364,
      197,  201,  201,  198,  361,  197,  202,  202,  360,  200,
      251,  251,  252,  252,  201,  254,  254,  255,  255,  202,
      358,  355,  354,  251,  353,  252,  352,  350,  254,  349,
      255,  380,  380,  380,  380,  381,  381,  381,  381,  383,
      347,  346,  383,  384,  345,  384,  384,  385,  344,  385,
      385,  341,  340,  339,  338,  337,  336,  335,  332,  331,

      330,  326,  324,  323,  322,  320,  319,  317,  315,  311,
      310,  309,  307,  306,  304,  303,  302,  300,  299,  298,
      296,  295,  293,  292,  290,  289,  288,  287,  286,  284,
      283,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  270,  269,  268,  267,  266,  261,  260,  259,  258,
      257,  256,  253,  250,  249,  246,  245,  243,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  231,  229,
      228,  227,  226,  224,  223,  222,  221,  218,  217,  216,
      215,  214,  212,  209,  208,  207,  206,  205,  204,  203,
      196,  193,  192,  191,  189,  188,  187,  186,  185,  184,

      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      172,  171,  170,  169,  167,  165,  164,  163,  162,  161,
      160,  159,  158,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  139,  128,  124,  123,  122,
      120,  119,  118,  116,  115,  114,  113,  112,  110,  108,
      107,  106,  105,  104,  103,  102,  101,  100,   99,   98,
       97,   96,   94,   93,   92,   91,   90,   89,   88,   87,
       73,   64,   61,   58,   57,   53,   51,   50,   47,   44,
       42,   31,   29,   20,   16,   12,   11,    9,    7,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,

      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
    /* ---
    Disciplina de Compiladores
    ---
    Trabalho realizado por

    Leonardo Duarte
    2023213089

    Rui Ribeiro
    202118947

    --- */

    /* place here any C variables and definitions */
    #include <stdio.h>
    #include <string.h>
    #include "y.tab.h"
    #include "semantic.h"

    int row = 1;
    int column = 0;

    #define YY_USER_ACTION do { \
        yylloc.first_line = row; \
        yylloc.first_column = column + 1; \
        yylloc.last_line = row; \
        yylloc.last_column = column + yyleng; \
        column += yyleng; \
    } while (0);

    char str_lit[1024];
    char * str_ptr;

    int str_err = 0;

    int str_row = 0;
    int str_col = 0;
    int com_row = 0;
    int com_col = 0;

    int flag_l = 0;
    int lex_only = 0;
    int flag_t = 0;
    int flag_s = 0;

#line 731 "lex.yy.c"

#line 733 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRLITERAL 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 59 "jucompiler.l"


#line 955 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 380 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 490 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{ ; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 62 "jucompiler.l"
{ row++; column = 0; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{ if(flag_l) printf("BOOLLIT(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return BOOLLIT; } }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "jucompiler.l"
{ if(flag_l) printf("INT\n");        if (!lex_only) return INT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{ if(flag_l) printf("DOUBLE\n");     if (!lex_only) return DOUBLE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{ if(flag_l) printf("IF\n");         if (!lex_only) return IF; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "jucompiler.l"
{ if(flag_l) printf("ELSE\n");       if (!lex_only) return ELSE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "jucompiler.l"
{ if(flag_l) printf("WHILE\n");      if (!lex_only) return WHILE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{ if(flag_l) printf("RETURN\n");     if (!lex_only) return RETURN; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{ if(flag_l) printf("PLUS\n");       if (!lex_only) return PLUS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{ if(flag_l) printf("MINUS\n");      if (!lex_only) return MINUS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "jucompiler.l"
{ if(flag_l) printf("STAR\n");       if (!lex_only) return STAR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "jucompiler.l"
{ if(flag_l) printf("DIV\n");        if (!lex_only) return DIV; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{ if(flag_l) printf("MOD\n");        if (!lex_only) return MOD; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{ if(flag_l) printf("ASSIGN\n");     if (!lex_only) return ASSIGN; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{ if(flag_l) printf("LPAR\n");       if (!lex_only) return LPAR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{ if(flag_l) printf("RPAR\n");       if (!lex_only) return RPAR; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{ if(flag_l) printf("COMMA\n");      if (!lex_only) return COMMA; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{ if(flag_l) printf("AND\n");        if (!lex_only) return AND; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{ if(flag_l) printf("EQ\n");         if (!lex_only) return EQ; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{ if(flag_l) printf("LE\n");         if (!lex_only) return LE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{ if(flag_l) printf("GE\n");         if (!lex_only) return GE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{ if(flag_l) printf("LT\n");         if (!lex_only) return LT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{ if(flag_l) printf("GT\n");         if (!lex_only) return GT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{ if(flag_l) printf("LBRACE\n");     if (!lex_only) return LBRACE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{ if(flag_l) printf("RBRACE\n");     if (!lex_only) return RBRACE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{ if(flag_l) printf("LSQ\n");        if (!lex_only) return LSQ; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{ if(flag_l) printf("RSQ\n");        if (!lex_only) return RSQ; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{ if(flag_l) printf("NE\n");         if (!lex_only) return NE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "jucompiler.l"
{ if(flag_l) printf("NOT\n");        if (!lex_only) return NOT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{ if(flag_l) printf("OR\n");         if (!lex_only) return OR; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "jucompiler.l"
{ if(flag_l) printf("SEMICOLON\n");  if (!lex_only) return SEMICOLON; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{ if(flag_l) printf("ARROW\n");      if (!lex_only) return ARROW; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{ if(flag_l) printf("RSHIFT\n");     if (!lex_only) return RSHIFT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{ if(flag_l) printf("LSHIFT\n");     if (!lex_only) return LSHIFT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{ if(flag_l) printf("XOR\n");        if (!lex_only) return XOR; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{ if(flag_l) printf("BOOL\n");       if (!lex_only) return BOOL; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "jucompiler.l"
{ if(flag_l) printf("CLASS\n");      if (!lex_only) return CLASS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{ if(flag_l) printf("DOTLENGTH\n");  if (!lex_only) return DOTLENGTH; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "jucompiler.l"
{ if(flag_l) printf("PRINT\n");      if (!lex_only) return PRINT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "jucompiler.l"
{ if(flag_l) printf("PARSEINT\n");   if (!lex_only) return PARSEINT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{ if(flag_l) printf("PUBLIC\n");     if (!lex_only) return PUBLIC; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{ if(flag_l) printf("STATIC\n");     if (!lex_only) return STATIC; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "jucompiler.l"
{ if(flag_l) printf("STRING\n");     if (!lex_only) return STRING; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{ if(flag_l) printf("VOID\n");       if (!lex_only) return VOID; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 110 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 111 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 112 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 114 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 116 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 117 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 118 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 119 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 120 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 121 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 122 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 123 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 124 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 125 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 126 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 127 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 128 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 129 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 130 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 131 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 132 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 133 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 134 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 135 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 136 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 137 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 138 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 139 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 140 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 141 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 142 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 143 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 144 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 145 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 146 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 147 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 148 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 149 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 150 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 151 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 152 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 153 "jucompiler.l"
{if(flag_l) printf("RESERVED(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return RESERVED; }}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 157 "jucompiler.l"
{ if (flag_l) printf("IDENTIFIER(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return IDENTIFIER; } }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 159 "jucompiler.l"
{ if (flag_l) printf("NATURAL(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return NATURAL; } }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 161 "jucompiler.l"
{ if (flag_l) printf("DECIMAL(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return DECIMAL; } }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 162 "jucompiler.l"
{ if (flag_l) printf("DECIMAL(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return DECIMAL; } }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 163 "jucompiler.l"
{ if (flag_l) printf("DECIMAL(%s)\n", yytext); if (!lex_only) { yylval.lexeme = strdup(yytext); return DECIMAL; } }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 166 "jucompiler.l"
{ BEGIN(COMMENT); com_row = row; com_col = column - yyleng + 1; }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 167 "jucompiler.l"
{ row++; column = 0; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 168 "jucompiler.l"
{ ; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 169 "jucompiler.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 170 "jucompiler.l"
{ printf("Line %d, col %d: unterminated comment\n", com_row, com_col); BEGIN(INITIAL); return 0; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 172 "jucompiler.l"
{ ; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 174 "jucompiler.l"
{
            BEGIN(STRLITERAL);
            str_err = 0;
            str_ptr = str_lit;
            str_row = row;
            str_col = column - yyleng + 1;
            *str_ptr++ = '\"';

        }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 184 "jucompiler.l"
{
            *str_ptr++ = '\"';

            *str_ptr = '\0';

            if (!str_err) {
                // if (flag_l) printf("STRLIT(\"%s\")\n", str_lit);
                if (flag_l) printf("STRLIT(%s)\n", str_lit);

                if (!lex_only) {
                    yylval.lexeme = strdup(str_lit);
                    BEGIN(INITIAL); 
                    yytext = str_lit;
                    return STRLIT; 
                }
            }
            BEGIN(INITIAL);
        }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 203 "jucompiler.l"
{ 
            *str_ptr++ = yytext[0];
            *str_ptr++ = yytext[1];
        }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 208 "jucompiler.l"
{
            printf("Line %d, col %d: invalid escape sequence (%s)\n", row, column - yyleng + 1, yytext);
            str_err = 1;
        }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 213 "jucompiler.l"
{
            printf("Line %d, col %d: invalid escape sequence (\\)\n", row, column - yyleng + 1);
            str_err = 1;
        }
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 218 "jucompiler.l"
{
            printf("Line %d, col %d: unterminated string literal\n", str_row, str_col);
            row++; column = 0;
            BEGIN(INITIAL);
        }
	YY_BREAK
case YY_STATE_EOF(STRLITERAL):
#line 224 "jucompiler.l"
{
            printf("Line %d, col %d: unterminated string literal\n", str_row, str_col);
            BEGIN(INITIAL);
            return 0;
        }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 230 "jucompiler.l"
{
            char *yy_ptr = yytext;
            while ( *yy_ptr ) {
                    *str_ptr++ = *yy_ptr++;
            }
        }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 238 "jucompiler.l"
{ printf("Line %d, col %d: illegal character (%s)\n", row, column - yyleng + 1, yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 241 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1610 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 380 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 380 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 379);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 241 "jucompiler.l"

extern int yylex();
extern int yyparse();
extern void print_final_ast();
extern int get_syntax_errors();
extern int run_semantic(int print_tables);

void meta01() {
    lex_only = 1;
    yylex();
}

void meta01_l() {
    flag_l = 1;
    meta01();
}

void meta02() {
    yyparse();
    print_final_ast();
}

void meta02_t() {
    flag_t = 1;
    meta02();
}

void meta03() {
    yyparse();
    if (get_syntax_errors() == 0) {
        run_semantic(flag_s);
    }
    print_final_ast();
}

void meta03_s() {
    flag_s = 1;
    flag_t = 1;
    meta03();
}

int main(int argc, char **argv) {

    if (argc == 1){
        // meta mais recente
        meta03();
    } else if (argc > 1 && strcmp(argv[1], "-e1") == 0) {
        meta01();
    } else if (argc > 1 && strcmp(argv[1], "-l") == 0) {
        meta01_l();
    } else if (argc > 1 && strcmp(argv[1], "-e2") == 0) {
        meta02();
    } else if (argc > 1 && strcmp(argv[1], "-t") == 0) {
        meta02_t();
    } else if (argc > 1 && strcmp(argv[1], "-e3") == 0) {
        meta03();
    } else if (argc > 1 && strcmp(argv[1], "-s") == 0) {
        meta03_s();
    }

    return 0;
}


int yywrap() { 
    return 1;
}

